### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by shabbirbashir** [iDefense/ig-query#5]
C:\Users\<my_user_name>\Desktop\ig-query-master>ig-query.py
  File "C:\Users\<my_user_name>\Desktop\ig-query-master\ig-query.py", line 103
    print json.dumps(r.json(), indent=2)
             ^
SyntaxError: invalid syntax

**Comment by krmaxwell** [comment]
Yup, all these `print` issues will be related to the Python 3 compatibility. My intention is to fix these on Friday.
